import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/sidebar";
import { SidebarProvider } from "@/contextAPI/SidebarContext";
import ChildrenContainer from "@/utils/ChildrenContainer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "efandex-dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
        <Navbar />
        <div className="flex w-full mt-16">
        <Sidebar />
          <ChildrenContainer>{children}</ChildrenContainer>
        </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
